Benji377/OpenMusic

app/build.gradle
Changed versionCode and versionName to the current release
=> Fixed versioning

app/src/main/java/com/example/SocyMusic/PlayerFragment.java
Added onLayoutChange listener. It programmatically detects and sets the height and width of the textview which should fix the issue.
=> Fix issue #22

app/src/main/java/com/example/SocyMusic/PlayerFragment.java
The player now loops around the songs, which means that when it gets to the last song it starts at the first again and vice versa.
=> Fixed issue #35

app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/MediaPlayerService.java, app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/PlayerFragment.java, app/src/main/java/com/example/SocyMusic/SongsData.java
Made mediaPlayer part of a utility class accessible everywhere rather than part of the PlayerFragment so now app is more stable. .
Also made the song thumbnail animation rotate the other way when Play Previous button is pressed. Small touch :D
=> Fixed crashing when app is closed and reopened quickly bug

app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/PlayerFragment.java
Fixed bug where song title reloads every time user pauses and made action bar hide menu items when bottom sheet is expanded, solving issue #43.
=> Minor changes with action bar and song title bug fix

app/src/main/res/layout/activity_main.xml
Added margin at the bottom of the Listview. Fixed issue #47
=> Update activity_main.xml and fix #47

app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/SongsData.java
The app now successfully finds songs on external storage devices if the files are in the following path:
/SDCARD/Android/data/com.example.musicplayer/files/
But strangely the songs don't get displayed. Look at Logcat to see what paths and what files get found.
=> Tried to add a way to get files from the SD-card

app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/res/values/colors.xml, app/src/main/res/values/pop_up_window.xml
Added missing colorAccent attribute which was causing the app to cras on some devices.
Changed the context because it was crashing the app when peple where clicking on links on the popup
=> Fixed issue #56 and minor changes

app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/SongsData.java
I added the functionality that once the last song has finished playing, the first one plays again, same vice versa. This just adds the commodity of not needing to start the first song again once you reach the end.
I also created a new method to add songs more directly to the songsList, but I haven't tested it yet. This should help in fixing issue #58
=> Song looping and new method in SongsData

app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/SongsData.java
I extended the playNext and playPrev functions to detect if the song is in repeat mode or not and act accordingly
=> Made repeat actually work, fixed issue #64

app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/PlayerFragment.java, app/src/main/java/com/example/SocyMusic/SongsData.java, app/src/main/res/drawable/ic_shuffle.xml, app/src/main/res/drawable/ic_shuffle_selected.xml, app/src/main/res/drawable/shuffle_button_selector.xml, app/src/main/res/layout/fragment_player.xml
Added the shuffle button symmetrically to the repeat button and added its functionality
=> Added shuffle button for #69

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/MediaPlayerService.java, app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/QueueFragment.java, app/src/main/res/layout/fragment_player.xml
Should address issue #65. Tested on a device with API 29. 
Also some small bug fixes with playback in MainActivity.
=> Added support for media buttons from bluetooth devices. 

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/SocyMusic/MainActivity.java, app/src/main/java/com/example/SocyMusic/MediaPlayerService.java, app/src/main/java/com/example/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/example/SocyMusic/PlayerFragment.java, app/src/main/java/com/example/SocyMusic/QueueFragment.java, app/src/main/java/com/example/SocyMusic/SettingsActivity.java, app/src/main/java/com/example/SocyMusic/SettingsFragment.java, app/src/main/java/com/example/SocyMusic/Song.java, app/src/main/java/com/example/SocyMusic/SongsData.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/fragment_player.xml, app/src/main/res/menu/main.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
For now it's not functional. I wanted to have a setting for library root path  but I couldn't get that to work. I'm not so sure it's what we should do anyway. I have some thoughts I'll put to a new issue. Also I put a setting there for themes but it's not functional yet either.
=> Added a SettingsActivity.

docs/index.md
As of discussion #78, we agreed on a naming convention for various reasons that you can go and read there.
=> Added naming convention section

app/src/main/java/com/example/SocyMusic/SettingsFragment.java, app/src/main/java/com/example/SocyMusic/Song.java, app/src/main/java/com/example/SocyMusic/SongsData.java, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
Removed unused imports and added some basic day/night theme
=> Minor changes

.idea/jarRepositories.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/musicplayer/SocyMusic/DirBrowserActivity.java, app/src/main/java/com/musicplayer/SocyMusic/DirBrowserFragment.java, app/src/main/java/com/musicplayer/SocyMusic/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/SettingsFragment.java, app/src/main/java/com/musicplayer/SocyMusic/SocyMusicApp.java, app/src/main/java/com/musicplayer/SocyMusic/SongsData.java, app/src/main/res/drawable/ic_folder.xml, app/src/main/res/layout/activity_dir_browser.xml, app/src/main/res/layout/fragment_dir_browser.xml, app/src/main/res/layout/list_item_dir_browser.xml, app/src/main/res/menu/dir_browser.xml, app/src/main/res/menu/main.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, build.gradle
Also some minor refactoring with the IDs in the menu resources.
=> Adds a directory browser for library directories, addressing issue #80.

app/src/main/java/com/musicplayer/SocyMusic/Playlist.java, app/src/main/java/com/musicplayer/SocyMusic/PlaylistFragment.java, app/src/main/java/com/musicplayer/SocyMusic/SongsData.java, app/src/main/res/layout/fragment_playlist.xml
The bug should now hopefully be fixed. I will test it on my phone too, but it should be ok.
I also had to remake the playlist class as I just found out that the Mediastore playlist class is deprecated and should not be used. They suggest using M3U-files instead so that's what I am going for now.
=> Fixed bug #98 and playlist refactoring

app/src/main/res/drawable/ic_favorite.xml, app/src/main/res/drawable/ic_favorite_selected.xml, app/src/main/res/drawable/ic_playlist_add.xml, app/src/main/res/drawable/playlist_add_check.xml, app/src/main/res/layout/fragment_player_new.xml, app/src/main/res/values/strings.xml
Added icons and prepared player fragment to be used
=> Design change

app/src/main/java/com/musicplayer/SocyMusic/PlayerFragment.java, app/src/main/res/drawable/player_background.xml, app/src/main/res/layout/fragment_player.xml, app/src/main/res/layout/fragment_player_old.xml
The new fragment is now functional, but I still need to add the functionality for the new buttons and add a long-press action on the previous and next buttons. I also set the background to complete black for now and am still searching for a way to make it look cool.
=> New fragment_player and minor changes

app/src/main/java/com/musicplayer/SocyMusic/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/MediaPlayerUtil.java, app/src/main/java/com/musicplayer/SocyMusic/PlayerFragment.java, app/src/main/res/layout/fragment_player.xml, app/src/main/res/layout/pager_item_song.xml
This allows swiping to next/previous song
=> Adds a Viewpager to PlayerFragment 

app/build.gradle, app/src/main/java/com/musicplayer/SocyMusic/Playlist.java, app/src/main/java/com/musicplayer/SocyMusic/ui/player/PlayerFragment.java
I tested this on an external project and it should be working just fine. Now we just need to implement the Fragment which lists all playlists and we should be good to go. I am just very bad with Fragments so this is going to be fun.
Afterwards we just need to test it and if needed fix any issues.
=> Playlist is working now

app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java
Added a Sharedpreferences listener that recreates the Mainactivity every time the theme setting gets changed
=> Fixed issue #128

app/src/main/res/layout/fragment_player.xml, app/src/main/res/values/tags.xml, app/src/main/res/values/themes.xml
By adding a custom item value to the themes the background is now also all done and set. Maybe we could add some more colors in the future and probably adjust the color values right now. Also please note that the big round red music circle can't be changed since it's a fixed image and it will be replaced by the Song thumbnail in the future.
=> Fixed issue #131

.github/workflows/greetings.yml
Greets new user when they contribute for the first time on this repo. Messages are customizable
=> New automation workflow

.github/workflows/gradle.yml
I have no idea how this actually works, but what I hope it does is build the apk automatically. This would add the possibility of just downloading the apk without release for testing
=> Automatic builder

CONTRIBUTING.md
Warning! This is just a template fetched from https://github.com/github/docs/blob/16b9266cd58841f3cd4f31a8e59f20a60a23c1d5/CONTRIBUTING.md
It is still a work in progress, don't use it for now!
=> Created Contributing TEMPLATE

app/src/main/res/values-it/strings.xml
Using this guide: https://developer.android.com/guide/topics/resources/localization#defaults-r-important I added the italian version of the available strings
=> Added italian translation

app/src/main/res/values-de/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values/strings.xml
=> Translated the strings.xml file in German and Italian

app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/player/PlayerFragment.java
It was surprisingly easy to do. I just had to call the already existing method from the MainActivity. To do this the method had to be set to public.
=> Fix issue #134

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/musicplayer/SocyMusic/ui/player/PlayerFragment.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/Playlist.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistFragment.java
After a lot of headaches, I finally managed to at least get the Playlist functionality started. It is now able to write data to files and create new files.
=> Playlist finally started

.gitignore, .idea/gradle.xml, .idea/runConfigurations.xml, app/src/main/java/com/musicplayer/SocyMusic/ui/dir_browser/DirBrowserActivity.java
I technically also added a new gitignore rule to avoid uploading .idea files, but I am not so sure if it works as intended since it seems like I am still able to upload .idea files
PS: @squivix you are a collaborator now right? This means you should be able to merge this pull request on your own now
=> Fixed theme on DirBrowser

app/src/main/java/com/musicplayer/SocyMusic/SocyMusicApp.java, app/src/main/java/com/musicplayer/SocyMusic/ui/dir_browser/DirBrowserActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/player/PlayerFragment.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/settings/SettingsActivity.java, app/src/main/java/com/musicplayer/SocyMusic/utils/AlertUtils.java, app/src/main/java/com/musicplayer/SocyMusic/utils/ThemeChanger.java, app/src/main/res/values-night/themes.xml, build.gradle
By keeping all the themes in one place it is simpler to add themes to the switch case because you just need to edit one file and not three or four at once. We also solve a coding problem by avoiding the usage of the same code multiple times.
=> Centralized themes

app/src/main/AndroidManifest.xml, app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistActivity.java, app/src/main/res/menu/main.xml, app/src/main/res/menu/playing.xml, app/src/main/res/menu/playlist.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Removed unnecessary new theme and added simple `actionbar.hide()` option in PlaylistActivity. This still didn't solve the problem... Still working on it.
=> Fixing issue #174

.idea/misc.xml, app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistActivity.java, app/src/main/res/layout/content_main.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
Toolbar can be changed how we like it with much more ease than the actionbar and I therefore changed it. Th colors are now fixed, the only thing I still need to manually force is the statusbar color. 
I am also working on fixing issue #183.
=> Replaced actionbar with toolbar

app/src/main/java/com/musicplayer/SocyMusic/MediaPlayerService.java, app/src/main/java/com/musicplayer/SocyMusic/data/Song.java, app/src/main/java/com/musicplayer/SocyMusic/ui/album/AlbumActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/album/AlbumSongHolder.java, app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistSongHolder.java, app/src/main/res/layout/card_item_album.xml, app/src/main/res/layout/content_main.xml, app/src/main/res/layout/pager_item_song.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
Fixes AlbumActivity crash in Android 11, PlayerActivity crash in API 31, and changed MainActivity TabLayout indicator color to colorPrimaryDark . Plus some renaming.
=> Crash fixes and color touches

app/build.gradle, app/src/main/java/com/musicplayer/SocyMusic/utils/ImportExportUtils.java
This should allow users to export databases, and settings for backup or later use. The purpose is to be able to export playlists in database and m3u format and settings in XML and JSON format.
I think we could use Room to do this easily, but for now, I will be using simple Java files output and input streams
=> Export and import settings/playlists

app/src/main/AndroidManifest.xml, app/src/main/java/com/musicplayer/SocyMusic/MediaPlayerService.java, app/src/main/java/com/musicplayer/SocyMusic/ui/player_fragment_host/PlayerFragmentHost.java, app/src/main/java/com/musicplayer/SocyMusic/utils/BluetoothUtil.java
The app now detects when a Bluetooth device connects or disconnects from the device. This allows the app to pause music playback when your headphones disconnect for example.
I added a new class that listens for changes in the Bluetooth connections. It then updates the Mediaplayer through the MediaplayerUtil.
There are two open issues to this:
1. The app seems to take a while until it gets a Bluetooth disconnection signal
2. The playerfragment doesn't update the play/pause button
The UI is not actually that big of a problem since we will redesign a big part of it anyway, but the slowness might become an issue. Also, this might need to be tested further with more and multiple devices to detect other issues.
=> Added new Bluetooth functionality

app/src/main/AndroidManifest.xml, app/src/main/java/com/musicplayer/SocyMusic/SocyMusicApp.java, app/src/main/java/com/musicplayer/SocyMusic/ui/album/AlbumActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/main/MainActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/playlist/PlaylistActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/settings/SettingsActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/settings/SettingsFragment.java, app/src/main/java/com/musicplayer/SocyMusic/ui/sleeptime/SleepTimeActivity.java, app/src/main/java/com/musicplayer/SocyMusic/ui/sleeptime/SleepTimeFragment.java, app/src/main/java/com/musicplayer/SocyMusic/utils/PreferenceUtils.java, app/src/main/res/layout/activity_sleeptime.xml, app/src/main/res/layout/fragment_sleeptime.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
As requested by some of you, you can now set a time at which the app will stop and close itself. You can also deactivate this functionality, it will be so by default.
I added a new option to the settings which allow you to access a TimePicker. You can then enter your time and/or activate or deactivate the functionality using a switch below.
The time will then be tracked by the app. As soon as the time gets reached the app gets closed and the music stops playing.
We could improve it by asking the user before closing the app if he actually wants to close it or not. Maybe add a switch to activate or deactivate alert messages.
=> Added sleepTime function

README.md
_Describe the problem or feature in addition to a link to the issues._
_How does this change address the problem?_
_Describe the research stage_
_Links to blog posts, patterns, libraries or addons used to solve this problem_
=> Added Stargaze
